### ISSUE TITLE
admin mail notification system

### ISSUE THREAD

**Issue by stw222** [MultiChat/Development#91] opened 2020-04-23 01:38 UTC
**Is your feature request related to a problem? Please describe.**
People dont seem to like to use external software when playing a game unless they are a part of the hardcore audience.
We make lots of announcements on our discord server where only like half of our playerbase has joined

**Describe the solution you'd like**
a command kind of like EssentialsX's /mail command but its used for admins to send announcements to players and players would use something like /amail clear to get rid of the notifications.
notifications for announcements would appear when they join the server or when they switch servers

**Describe alternatives you've considered**
essentials /mail would almost work except it doesnt work cross server in networks

**Additional context**

**Comment by OllieMartin** [comment] 2020-04-23 10:51
I believe this is a duplicate of #77 but with a slightly different usecase. It might be possible to implement some sort of "priority" mail with the mail system where admin mails can show up with more prominance for example.

**Closed** 2020-04-25 15:42 UTC
Labels: duplicate, enhancement
