### ISSUE TITLE
email system

### ISSUE THREAD

**Issue by Lucifer187** [MultiChat/Development#152] opened 2020-12-01 12:34 UTC
at the beginning i was confused with the plugin (but that was my mistake) but now i'm happy, what i think is particularly great is that you can use symbols.

is it possible to include a mail system in the next update and a separate log folder for all players of private messages?

**Comment by Gadsee** [comment] 2021-01-04 11:31
Duplicate of #77

**Closed by Gadsee** 2021-01-04 11:31 UTC
