### ISSUE TITLE
Feature request: Add a config option to exclude certain servers from MultiChat as a whole, rather than just global chat.

### ISSUE THREAD

**Issue by ryan-bing** [MultiChat/Development#140] opened 2020-08-07 00:12 UTC
I want to exclude certain servers from MultiChat to control network join/leave messages.

I want to create the illusion that server A and B are the same server. So, when a player joins the Hub server, it will not display any network leave/join (as this server would be excluded from MultiChat). When they walk in the portal for server A, it will display a network join message. When they switch to server B, no message will be shown. When they leave server B to go to the hub, the network leave message will be displayed.

**Comment by OllieMartin** [comment] 2020-08-07 12:00
Hi there, would you say this is a duplicate of: https://github.com/MultiChat/Development/issues/134

I think that you have the same end goal?

Please correct me if I am wrong!

**Comment by ryan-bing** [comment] 2020-08-07 12:55
Sorry, yes this a duplicate of #134.

**Comment by OllieMartin** [comment] 2020-08-07 13:03
Not a problem at all, I just wanted to make sure!

Its useful to see your use case as well. So it will help me in deciding how to implement it. Any further discussion will take place in #134 👍

**Closed by OllieMartin** 2020-08-07 13:03 UTC
Labels: duplicate, more info needed, request
