### ISSUE TITLE
Use connection pool in database connections to prevent timeout

### ISSUE THREAD

**Issue by itsmeow** [MultiChat/Development#92] opened 2020-04-23 10:25 UTC
**Describe the bug**
Upon a player joining again, occasionally a duplicate key will be inserted into the database causing a large log error 

**Full startup log of affected servers**
```
[09:49:13 WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
[09:49:13 WARN]:
[09:49:13 WARN]: The last packet successfully received from the server was 32,772,975 milliseconds ago. The last packet sent successfully to the server was 33 milliseconds ago.
[09:49:13 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:49:13 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[09:49:13 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:49:13 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[09:49:13 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[09:49:13 WARN]: at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[09:49:13 WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3517)
[09:49:13 WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3417)
[09:49:13 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3860)
[09:49:13 WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[09:49:13 WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[09:49:13 WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[09:49:13 WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
[09:49:13 WARN]: at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
[09:49:13 WARN]: at xyz.olivermartin.multichat.database.MySQLDatabase.safeQuery(MySQLDatabase.java:105)
[09:49:13 WARN]: at xyz.olivermartin.multichat.spigotbridge.SQLNameManager.existsUUID(SQLNameManager.java:292)
[09:49:13 WARN]: at xyz.olivermartin.multichat.spigotbridge.SQLNameManager.registerPlayer(SQLNameManager.java:187)
[09:49:13 WARN]: at xyz.olivermartin.multichat.spigotbridge.NameManager.onLogin(NameManager.java:297)
[09:49:13 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor355.execute(Unknown Source)
[09:49:13 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[09:49:13 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[09:49:13 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[09:49:13 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.PlayerList.attemptLogin(PlayerList.java:549)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:154)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1295)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1132)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940)
[09:49:13 WARN]: at java.lang.Thread.run(Thread.java:748)
[09:49:13 WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[09:49:13 WARN]: at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2969)
[09:49:13 WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427)
[09:49:13 WARN]: ... 26 more
[09:49:13 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'a34fae0b-de27-427e-b913-ad51145036ae' for key 'PRIMARY'
[09:49:13 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:49:13 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[09:49:13 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:49:13 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[09:49:13 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[09:49:13 WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:408)
[09:49:13 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[09:49:13 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[09:49:13 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[09:49:13 WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[09:49:13 WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[09:49:13 WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[09:49:13 WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
[09:49:13 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133)
[09:49:13 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2067)
[09:49:13 WARN]: at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5175)
[09:49:13 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2052)
[09:49:13 WARN]: at xyz.olivermartin.multichat.database.MySQLDatabase.safeUpdate(MySQLDatabase.java:120)
[09:49:13 WARN]: at xyz.olivermartin.multichat.spigotbridge.SQLNameManager.registerPlayer(SQLNameManager.java:214)
[09:49:13 WARN]: at xyz.olivermartin.multichat.spigotbridge.NameManager.onLogin(NameManager.java:297)
[09:49:13 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor355.execute(Unknown Source)
[09:49:13 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[09:49:13 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[09:49:13 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[09:49:13 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.PlayerList.attemptLogin(PlayerList.java:549)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:154)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1295)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1132)
[09:49:13 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940)
[09:49:13 WARN]: at java.lang.Thread.run(Thread.java:748) 
```

**To Reproduce**
1. Leave server running a bit
2. Leave
3. Rejoin after a bit

**Expected behavior**
Should use UPDATE or not run query if the player is already inserted

**Platform and Versions (please complete the following information):**
 - OS: Linux CentOS 7
 - Java Version: 1.8_121
- MultiChat Version: 1.8.1
 - Proxy Version: Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326
 - Local Server Version: 1.15.2-paper-171

**Comment by OllieMartin** [comment] 2020-04-23 10:44
This error is very strange. It is not originally caused by a bug in MultiChat's code. Your server lost conncetion to its database which caused this first error:

" com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
[09:49:13 WARN]:"

This first error happened when we were checking if the UUID already existed:

[09:49:13 WARN]: at xyz.olivermartin.multichat.database.MySQLDatabase.safeQuery(MySQLDatabase.java:105)
[09:49:13 WARN]: at xyz.olivermartin.multichat.spigotbridge.SQLNameManager.existsUUID(SQLNameManager.java:292)
[09:49:13 WARN]: at xyz.olivermartin.multichat.spigotbridge.SQLNameManager.registerPlayer(SQLNameManager.java:187)
[09:49:13 WARN]: at xyz.olivermartin.multichat.spigotbridge.NameManager.onLogin(NameManager.java:297)

Then, for some reason, the code continued running despite encountering that first error when your server lost connection to its database. And because the code was interrupted when checking if the UUID was in the database, it didn't see the UUID in the database so went to add it.

I am not 100% sure if this is something that I can fix or not in my code as it was due to a loss of connection to the database.

There might be a way I can catch that kind of error, I will investigate

**Comment by itsmeow** [comment] 2020-04-25 15:18
I doubt it's my SQL server considering it's hosted locally and has been running for weeks.
![image](https://user-images.githubusercontent.com/10366817/80283474-cb05a900-86e5-11ea-9eed-ce04ae330115.png)

Although, maybe of note is this line in my server's log:
```
2020-04-24T08:23:38.624477Z 49615 [Note] Aborted connection 49615 to db: 's1_multichat' user: '#######' host: '########' (Got timeout reading communication packets)
```

Possibly this is caused by not closing the connection after operations are complete?

**Comment by OllieMartin** [comment] 2020-04-25 15:40
From doing some research it looks to me like it is just MySQL timing out on the connection between the minecraft server and the MySQL server. You can change the timeout in your MySQL settings to make it timeout less often, I think it is a variable called 'wait_timeout'.

However, the database implementation in MultiChat is not particularly advanced at this stage. We do utilise a connection that is opened when you start your server, and closed when the server stops. This is going to be upgraded to using a connection pool soon. Hopefully that will solve your issue.

I will re-name this Issue to "use connection pool", as that should fix the timeout. It is being worked on and hopefully can be released in a version soon!

**Comment by OllieMartin** [comment] 2020-04-26 13:50
This has been fixed in the development versions and will be released ASAP

**Comment by OllieMartin** [comment] 2020-04-26 13:51
Please feel free to re-open the issue if there are still problems after trying the next version

**Closed by OllieMartin** 2020-04-26 13:50 UTC
Labels: bug, enhancement
